In [1]:
import numpy as np
arr=np.arange(1,10)

In [2]:
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9


# 1-searching an element in an array

In [3]:
n=int(input("enter the element to be searched"))                       
for i in arr:
    if i==n:
        print ("element is present")
        break
else:
    print("not found")

enter the element to be searched6
element is present


# 2- finding largest element in an array

In [4]:
for i in arr:
    l=i
    for j in arr:                                                     #try 1
        if j>l:
            l=j
            break
print(l)     

9


In [5]:
l=arr[0]
for i in arr:
    if i>l:                                                     #try 2
        l=i
print(l)    

9


# 3- finding smallest element in an array

In [6]:
s=arr[0]
for i in arr:                                               #3rd program
    if i<s:
        s=i
print(s)  

1


In [7]:
len(arr)

9

# 4- reversing an array

In [8]:
for i in range(0,len(arr)):
    t=arr[0]
    for j in range(1,len(arr)-i):                     #4th program
        arr[j-1]=arr[j]
        arr[j]=t
print(arr)        

[9 8 7 6 5 4 3 2 1]


# 

In [11]:
k=int(input("enter the k'th value"))                           #program 5
for i in range(0,k):            
    r=arr[0]                                                    #reversing from k'th position
    for j in range(1,k-i):
        arr[j-1]=arr[j]
        arr[j]=r
print(arr)        

enter the k'th value5
[5 6 7 8 9 4 3 2 1]


#  5-Reversing an array from k'th position

In [1]:
def rotate(arr,n,k):
    k=k%n
    for i in range(k):
        t=arr[n-1]
        for j in range(n-1,0,-1):
            arr[j]=arr[j-1]
        arr[0]=t
    return arr    

#  Reversing an array (try 2) 

In [29]:
l=len(arr)
n=int(l/2)                         #by diving array in two parts from middle and exchanging values
l=l-1
for i in range(n):
    t=arr[i]
    arr[i]=arr[l-i]
    arr[l-i]=t
print(arr)        

[9 8 7 6 4 3 2 1 5]


In [27]:
n=4
for i in range(n):
    print(i)
for i in range(0,n):
    print(i)

0
1
2
3
0
1
2
3
