In [1]:
#programming languages other than c and c++ can't directly ascess address
#c and c++ are very closely related to each other

In [2]:
import numpy as np

In [3]:
#creating an array
arr=np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr=np.array((1,2,3,4,5))

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
#datatype of an array

arr=np.array([1,2,3,4],dtype=float)

In [8]:
arr

array([1., 2., 3., 4.])

In [9]:
arr=np.array([1,2,3,4],dtype='S')

In [10]:
arr=np.arange(40)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [12]:
arr=np.arange(10,40)

In [13]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [14]:
arr=np.arange(10,40,2)

In [15]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [16]:
np.insert(arr,5,int(40))    #5th location   #check arguments using shift+tab on insert

array([10, 12, 14, 16, 18, 40, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [17]:
np.delete(arr,5)

array([10, 12, 14, 16, 18, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [18]:
np.insert(arr,0,100)

array([100,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,
        34,  36,  38])

In [19]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [20]:
#to overwrite wee will use assignment operator
arr=np.insert(arr,0,100)

In [21]:
arr

array([100,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,
        34,  36,  38])

In [22]:
arr=np.append(arr,50)    #adds value at the end
arr

array([100,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,
        34,  36,  38,  50])

In [25]:
arr=arr.astype(float)   #for operating various functions search numpy.org documentation

In [26]:
arr

array([100.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,  26.,  28.,
        30.,  32.,  34.,  36.,  38.,  50.])

In [27]:
arr=arr.astype(int) 
arr

array([100,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,
        34,  36,  38,  50])

In [29]:
mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
print(arr)

[100  10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  50]


In [31]:
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
mat1=np.array([[[1,2],(3,4)],[1,2],[(3,4),[2,4]]])
mat1

C:\Users\rishi\AppData\Local\Temp\ipykernel_6408\1694934729.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  mat1=np.array([[[1,2],(3,4)],[1,2],[(3,4),[2,4]]])


array([[list([1, 2]), (3, 4)],
       [1, 2],
       [(3, 4), list([2, 4])]], dtype=object)

In [34]:
#speed list
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]
c=[]
import time
start=time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)    

3.5594735145568848


In [39]:
arr1=np.arange(10000000)
arr2=np.arange(10000000,20000000)
import time
start=time.time()
c=arr1+arr2
print(time.time()-start)      #operators are implemented directly in numpy

0.027425765991210938


In [40]:
3.5594/0.02199

161.86448385629834

In [41]:
mat[1,1]

6

In [42]:
mat[1,2]

7

In [45]:
for i in range(3):
    print(mat[i,1])

2
6
10


In [50]:
d3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [51]:
d3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [52]:
d3[1,0]

array([ 9, 10, 11, 12])

In [53]:
d3[1,0,2]

11

In [55]:
dn=np.array([3],ndarray=5)

TypeError: array() got an unexpected keyword argument 'ndarray'

# Task 1:
1- searching an element in an array.
2- finding largest element in an array.
3- finding smallest element in an array.
4- reversing an array
5- rotating an array from k'th position

In [1]:
import numpy as np
arr=np.arange(10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
n=int(input("enter the element to be searched"))                             #1st program
for i in arr:
    if arr[i]==n:                                                              #all programs done from here on were just trial,
        print ("element is present at",i,"location in arr")                      #they are wrong, Refer TASK1
        break
else:
    print("not found")

enter the element to be searched4
element is present at 4 location in arr


In [5]:
for i in arr:
    l=arr[i]
    for j in arr:                                                     #2nd program
        if arr[j]>l:
            l=arr[j]
            break
print(l)            

9


In [6]:
l=arr[0]
for i in arr:
    if arr[i]>l:                                                     #2nd program
        l=arr[i]
print(l)        

9


In [7]:
s=arr[0]
for i in arr:for i in arr:
    for j in arr:
        t=arr[j-1]
        arr[j-1]=arr[j]
        arr[j]=t
        
print(arr)   
    if arr[i]<s:
        s=arr[i]
print(s)        

0


In [16]:
for i in arr:
    for j in arr:
        t=arr[j-1]
        arr[j-1]=arr[j]
        arr[j]=t
        
print(arr)        

[0 0 0 0 0 0 0 0 9 9]


In [17]:
len(arr)

10

In [18]:
for i in arr:
    print(i)

0
0
0
0
0
0
0
0
9
9


In [19]:
arr=np.arange(10)

In [20]:
for i in arr:
    print(i)

0
1
2
3
4
5
6
7
8
9
